### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by Farkie** [JohnathonKoster/math#10]
Hi Johnathon,

Just read through your solve method and spotted something which looks like a bug:

https://github.com/JohnathonKoster/math/blob/master/src/Flare/Math/Drivers/EvalMathDriver.php#L159

```
$temp  = $this->evaluatePostfixNotation($this->convertInfixToPostfix($matches[2]));
            if (($temp = false) == false)
            {
                return false;
            }
```

The IF block looks incorrect there. Not ran the code, but just thought I'd drop you a line.

**Comment by JohnathonKoster** [comment]
Definitely a bug. If you're interested in using the code, it was based on "Eval Math" by Mikes Kaufmann:

http://www.phpclasses.org/browse/file/11680.html

There is also a version available on GitHub:

https://github.com/Itangalo/evalmath.class.php/blob/master/matheval.class.php

This repo doesn't get a lot of attention anymore, and the ideas have been pulled into another project I work on in my spare time:

https://github.com/Stillat/Common/tree/master/src/Stillat/Common/Math
